# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Remove hostname configuration on loopback interface
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: ""
