# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Install system requirements
  become: true
  yum:
    name:
      - git
      - unzip
      - python39
      - jq
    state: present

- name: Ensure {{ python_bin }} pip is up to date
  become: true
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Remove existing nodejs
  become: true
  yum:
    name: nodejs
    state: absent
  when: "'ui' in features"

- name: Download Node.js package
  become: true
  get_url:
    url: https://nodejs.org/dist/v18.18.1/node-v18.18.1-linux-x64.tar.xz
    dest: /tmp/node-v18.18.1-linux-x64.tar.xz
  when: "'ui' in features"

- name: Extract Node.js package
  become: true
  unarchive:
    src: /tmp/node-v18.18.1-linux-x64.tar.xz
    dest: /opt
    remote_src: true
  when: "'ui' in features"

- name: Create symlink for /usr/bin/node, /usr/bin/npm, and /usr/bin/npx
  become: true
  file:
    src: "/opt/node-v18.18.1-linux-x64/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  loop:
    - node
    - npm
    - npx
  when: "'ui' in features"

- name: Check if firewalld is installed
  become: true
  yum:
    list: installed
  register: yum_installed

- name: Stop and disable firewalld
  become: true
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: "'firewalld' in (yum_installed.results | map(attribute='name'))"
