# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Template TDP UI service file
  become: true
  template:
    src: tdp-ui.service.j2
    dest: /usr/lib/systemd/system/tdp-ui.service

- name: Start TDP UI service
  become: true
  systemd:
    name: tdp-ui.service
    state: started
    enabled: yes
