# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Copy environment file to /etc/sysconfig/tdp-server
  become: true
  copy:
    src: "{{ project_dir }}/.env"
    dest: /etc/sysconfig/tdp-server
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  register: copy_result

- name: Remove 'export ' from /etc/sysconfig/tdp-server
  become: true
  replace:
    path: /etc/sysconfig/tdp-server
    regexp: '^export '
    replace: ''
  when: copy_result.changed

- name: Template TDP server service file
  become: true
  template:
    src: tdp-server.service.j2
    dest: /usr/lib/systemd/system/tdp-server.service

- name: Start TDP server service
  become: true
  systemd:
    name: tdp-server.service
    state: started
    enabled: yes
